# Generated by Django 5.2.11 on 2026-02-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='products_ca_sort_or_c50e68_idx',
            old_name='products_categ_sort_ord_1b2e5e_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_categor_9edb3d_idx',
            old_name='products_produ_category_9a1c2c_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_is_acti_ca4d9a_idx',
            old_name='products_produ_is_activ_7c4d4f_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_created_52f0d7_idx',
            old_name='products_produ_created__8f6e6e_idx',
        ),
        migrations.RenameIndex(
            model_name='productimage',
            new_name='products_pr_product_3d7874_idx',
            old_name='products_produt_product_1f3c5c_idx',
        ),
        migrations.RenameIndex(
            model_name='productimage',
            new_name='products_pr_sort_or_a10dc5_idx',
            old_name='products_produt_sort_or_6b7f3f_idx',
        ),
    ]
