# Generated by Django 5.2.11 on 2026-02-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_products_categ_sort_ord_1b2e5e_idx_products_ca_sort_or_c50e68_idx_and_more'),
        ('products', '0003_make_slug_unique'),
    ]

    operations = [
    ]
