# Generated by Django 6.0.2 on 2026-03-04 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='uniq_parent_name',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='price_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='stock_gte_0',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='products_ca_sort_or_c50e68_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_categor_9edb3d_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_acti_ca4d9a_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_created_52f0d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='productimage',
            name='products_pr_product_3d7874_idx',
        ),
        migrations.RemoveIndex(
            model_name='productimage',
            name='products_pr_sort_or_a10dc5_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
