# Generated by Django 6.0.2 on 2026-03-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productspecification_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productspecification',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order'], 'verbose_name': '商品图片', 'verbose_name_plural': '商品图片'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_sku_ca0cdc_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_acti_defdf1_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_categor_50f5f1_idx',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_main',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='库存'),
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_hot',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_recommend',
        ),
        migrations.RemoveField(
            model_name='product',
            name='market_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_warning',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='view_count',
        ),
    ]
