# Generated by Django 6.0.2 on 2026-03-09 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_productspecification_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(help_text='建议尺寸：1920x600像素', upload_to='banners/', verbose_name='图片')),
                ('link', models.URLField(blank=True, help_text='点击轮播图跳转的链接，可以是商品详情页或活动页', verbose_name='链接')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotRecommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_type', models.CharField(choices=[('home', '首页推荐'), ('category', '分类页推荐'), ('detail', '详情页推荐')], default='home', max_length=20, verbose_name='推荐类型')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommends', to='products.product', verbose_name='推荐商品')),
            ],
            options={
                'verbose_name': '热门推荐',
                'verbose_name_plural': '热门推荐',
                'ordering': ['recommend_type', 'sort_order'],
                'unique_together': {('product', 'recommend_type')},
            },
        ),
    ]
