# Generated by Django 6.0.2 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("pending_shipment", "Pending Shipment"),
                    ("pending_receipt", "Pending Receipt"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("refund_processing", "Refund Processing"),
                ],
                default="pending_payment",
                max_length=20,
            ),
        ),
    ]
