# Generated by Codex on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "待支付"),
                    ("pending_shipment", "待发货"),
                    ("pending_receipt", "待收货"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                    ("refund_processing", "售后中"),
                ],
                default="pending_payment",
                max_length=20,
            ),
        ),
    ]
