# Generated by Django 6.0.2 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="selected",
            field=models.BooleanField(default=True),
        ),
    ]
